name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: $
  VERCEL_PROJECT_ID: $

on:
  push:
    branches:
      - "master" # or main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$
      - name: Build Project Artifacts
        run: vercel build --prod --token=$
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=$
